# Very aggressive dev cache cleaning
R %h/.cache/go-build - - - 7d
R %h/go/pkg/mod - - - 30d
R %h/.cargo - - - 30d
R %h/.cache/pip - - - 30d
R %h/.npm - - - 30d
R %h/.pnpm-cache - - - 30d
R %h/.yarn - - - 30d
R %h/.cache/paru - - - 30d
R %h/.cache/yay - - - 30d
