# Go build cache
e %h/.cache/go-build - - - 7d
# Go mod cache
e %h/go/pkg/mod - - - 7d
# Cargo cache
e %h/.cargo/registry - - - 7d
# Pip cache
e %h/.cache/pip - - - 7d
# npm cache
e %h/.npm - - - 7d
# pnpm cache
e %h/.pnpm-store - - - 7d
# yarn cache
e %h/.cache/yarn - - - 7d
# paru cache
e %h/.cache/paru - - - 7d
# yay cache
e %h/.cache/yay - - - 7d
