# Very aggressive electron cache cleaning
R %h/.config/google-chrome/Default/Cache - - - 7d
R %h/.config/chromium/Default/Cache - - - 7d
R %h/.config/Slack/Cache - - - 7d
R %h/.config/Code/Cache - - - 7d
R %h/.config/Code/GPUCache - - - 7d
