# Chrome cache
e %h/.cache/google-chrome - - - 7d
# Chromium cache
e %h/.cache/chromium - - - 7d
# Slack cache
e %h/.config/Slack/Cache - - - 7d
# Code cache
e %h/.config/Code/Cache - - - 7d
e %h/.config/Code/GPUCache - - - 7d
