#!/usr/local/bin/zsh

alias docker="DOCKER_BUILDKIT=1 sudo docker"

alias dockerrm="docker container stop $(docker container ls -aq);docker ps -aq | xargs docker rm -f;docker container prune -f;docker images -aq | xargs docker rmi -f;docker image prune -a;docker volume prune -f;docker network prune -f;docker system prune -a"

dpath="$HOME/go/src/github.com/kpango/dotfiles"

alias kpbuild="cd $dpath&&docker build --pull=true --file=$dpath/Dockerfile -t kpango/dev:latest $dpath"

alias kpmove="cd $dpath"

alias devrun="sudo docker run --network host --cap-add=ALL \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/timezon:/etc/timezone:ro \
-v /etc/docker/daemon.json:/etc/docker/daemon.json \
-v $HOME/.docker/daemon.json:/root/.docker/daemon.json \
-v $HOME/.kube:/root/.kube \
-v $HOME/.netrc:/root/.netrc \
-v $HOME/.ssh:/root/.ssh \
-v $HOME/.zsh_history:/root/.zsh_history \
-v $HOME/go/src:/go/src:cached \
-v $HOME/Downloads:/root/Downloads \
-v $HOME/Documents:/root/Documents \
-v $dpath/init.vim:/root/.config/nvim/init.vim \
-v $dpath/tmux-kube:/root/.tmux-kube \
-v $dpath/tmux.conf:/root/.tmux.conf \
-v $dpath/zshrc:/root/.zshrc \
--name dev --rm -it kpango/dev:latest"
