title = " "
# command = /bin/zsh -c "tmux -S /tmp/tmux.sock -q has-session && exec tmux -S /tmp/tmux.sock -2 attach-session -d || exec tmux -S /tmp/tmux.sock -2 new-session -n$USER -s$USER@$(hostname)"
command = /bin/zsh
background-blur = false
wait-after-command = true
confirm-close-surface = false
quit-after-last-window-closed = true
shell-integration = zsh
shell-integration-features = no-cursor,no-sudo,title,ssh-env,no-ssh-terminfo,path

clipboard-read = allow
clipboard-write = allow
copy-on-select = clipboard

window-subtitle = working-directory
window-inherit-working-directory = true
window-theme = dark
window-padding-x = 3
window-padding-y = 0
window-padding-balance = true

background-opacity = 0.6
unfocused-split-opacity = 0.825

resize-overlay = never
resize-overlay-duration = 100ms

cursor-opacity = 0.4
cursor-style-blink = false

font-size = 14
font-family = "HackGen Console NF"
font-family-bold = "HackGen Console NF"
font-family-italic = "HackGen Console NF"
font-family-bold-italic = "HackGen Console NF"
font-feature = -dlig
grapheme-width-method = legacy

mouse-hide-while-typing = true
mouse-scroll-multiplier = 2

async-backend = io_uring
auto-update = download
auto-update-channel = tip

quick-terminal-animation-duration = 0.3
quick-terminal-size = 40%

gtk-opengl-debug = false
gtk-single-instance = false
gtk-titlebar = false

# custom-shader = ~/.config/ghostty/shaders/mnoise.glsl
# custom-shader-animation = always
# alpha-blending = linear

macos-non-native-fullscreen = true
macos-titlebar-style = transparent
macos-window-shadow = false

keybind = ctrl+shift+comma=reload_config
keybind = ctrl+equal=increase_font_size:1
keybind = ctrl+minus=decrease_font_size:1
keybind = ctrl+zero=reset_font_size

keybind = global:cmd+shift+t=toggle_quick_terminal

theme = zed_kpango
