# ── Plugins ────────────────────────────────────────────────────────────────────
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @cpu_interval 5
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# ── Modular config ─────────────────────────────────────────────────────────────
source-file ~/.tmux.conf.d/colors.conf
source-file ~/.tmux.conf.d/vars.conf
source-file ~/.tmux.conf.d/styles.conf
source-file ~/.tmux.conf.d/options.conf
source-file ~/.tmux.conf.d/keybindings.conf
source-file ~/.tmux.conf.d/status.conf

# ── TPM bootstrap ──────────────────────────────────────────────────────────────
run '~/.tmux/plugins/tpm/tpm'
