title   Arch Linux
linux   /vmlinuz-linux-zen
initrd  /amd-ucode.img
initrd  /initramfs-linux-zen.img
options root=PARTUUID=713a6825-7f30-4dc1-9515-aa15b9057fc0 resume=/dev/nvme1n1p1 rw quiet loglevel=1 nowatchdog acpi_backlight=none amd_iommu=on iommu=pt amd_pstate=disable cgroup_no_v1=all idle=nomwait pcie_aspm=off processor.max_cstate=1 nvidia_drm.fbdev=1 nvidia_drm.modeset=1 rd.systemd.show_status=auto rd.udev.log_priority=3 rd.driver.blacklist=nouveau usbcore.autosuspend=-1 vt.global_cursor_default=0 nvme_core.default_ps_max_latency_us=0 zswap.compressor=zstd zswap.enabled=1 zswap.max_pool_percent=10 zswap.zpool=z3fold
