# Zen2 Optimization Flags (Threadripper 3990X)
CFLAGS="-march=znver2 -mtune=znver2 -O2 -pipe -fno-plt -fexceptions -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
RUSTFLAGS="-C opt-level=2 -C target-cpu=znver2"
MAKEFLAGS="-j128"
BUILDENV=(!distcc color ccache check !sign)
PKGDEST=/tmp/pakku-kpango
