[colors.bright]
black = "#212121"
blue = "#20bbfc"
cyan = "#4fb8cc"
green = "#5fffaf"
magenta = "#ff55de"
red = "#fb007a"
white = "#f1f1f1"
yellow = "#f3e430"

[colors.cursor]
cursor = "#00ff00"
text = "#000000"

[colors.normal]
black = "#212121"
blue = "#006eff"
cyan = "#10cfdf"
green = "#10ff78"
magenta = "#ff3c79"
red = "#c30771"
white = "#e0e0e0"
yellow = "#a89c14"

[colors.primary]
background = "#2c292a"
foreground = "#f1f1f1"

[colors.selection]
background = "0x404040"
text = "0xeaeaea"

[font]
size = 17

[font.bold]
family = "HackGen35ConsoleNF"
style = "Bold"

[font.italic]
family = "HackGen35ConsoleNF"
style = "Italic"

[font.normal]
family = "HackGen35ConsoleNF"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Super"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Super"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
dynamic_padding = true
opacity = 1.2
