-- Hyprland configuration — kpango (Threadripper 3990X / RTX 2070 SUPER / Wayland)
-- requires: hyprland hypridle swww grim slurp mako wofi waybar fcitx5

-- ══════════════════════════════════════════════════════════════════════════════
-- ENVIRONMENT — NVIDIA RTX 2070 SUPER + Wayland
-- ══════════════════════════════════════════════════════════════════════════════

-- NVIDIA Wayland backend
-- Generated by hyprlang2lua + manual TODO resolution. All directives reviewed.

hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("__GL_GSYNC_ALLOWED", "1")

-- Wayland session
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- Electron apps (Slack, Discord, VSCode) → Wayland ネイティブ
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")

-- Qt → Wayland ネイティブ
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-- GTK (GTK4 は GDK_BACKEND のみ参照、GTK_BACKEND は GTK3 レガシー)
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("GTK_THEME", "Adwaita:dark")

-- Firefox / Thunderbird
hl.env("MOZ_ENABLE_WAYLAND", "1")

-- SDL / libinput
-- wayland,x11 順でフォールバック（ゲームの互換性確保）
hl.env("SDL_VIDEODRIVER", "wayland,x11")
hl.env("CLUTTER_BACKEND", "wayland")

-- NVIDIA パフォーマンス
-- フレームキューを 1 に絞りレンダリングレイテンシを削減（NVIDIA プロプライエタリ限定）
hl.env("__GL_MaxFramesAllowed", "1")
-- シェーダーをディスクキャッシュして初回起動時のスタッターを低減
hl.env("__GL_SHADER_DISK_CACHE", "1")
hl.env("__GL_SHADER_DISK_CACHE_PATH", "$HOME/.cache/nv-shader-cache")

-- GBM modifier negotiation を無効化（NVIDIA 環境での黒画面回避）
hl.env("AQ_NO_MODIFIERS", "1")

-- Cursor
hl.env("XCURSOR_THEME", "Adwaita")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- ══════════════════════════════════════════════════════════════════════════════
-- MONITORS
-- ══════════════════════════════════════════════════════════════════════════════
-- `hyprctl monitors` で実機の出力名・解像度を確認して調整すること。
-- kanshi は Hyprland 非対応のため monitor= で直接管理する。

-- Dell U4919DW (DP-1, DP-3): EDID 実測 10bpc 宣言確認済み → bitdepth 10 有効
-- LG ULTRAWIDE (HDMI-A-1): EDID bpc 未定義 (HDMI 8bpc デフォルト) → 10bit 強制は不安定のため見送り
hl.monitor({
    output = "eDP-1",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.monitor({
    output = "DP-1",
    mode = "preferred",
    position = "auto",
    scale = "1",
    bitdepth = 10,
})

hl.monitor({
    output = "DP-2",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.monitor({
    output = "DP-3",
    mode = "preferred",
    position = "auto",
    scale = "1",
    bitdepth = 10,
})

hl.monitor({
    output = "DP-4",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "1",
})

-- ══════════════════════════════════════════════════════════════════════════════
-- VARIABLES
-- ══════════════════════════════════════════════════════════════════════════════

local mainMod = "SUPER"
local menu = "wofi --show drun --config " .. HOME .. "/.config/wofi/config -i"
local chrome = "/usr/bin/google-chrome-beta"
local term_float = "ghostty"
-- NOTE: $(hostname) は Hyprland 変数内では展開されないためセッション名を $USER のみとする。
local term = "env GTK_IM_MODULE= LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8          ghostty -e " .. SHELL .. " -c          \"tmux -S /tmp/tmux.sock -q has-session &&           exec tmux -S /tmp/tmux.sock -2 attach-session -d ||           exec tmux -S /tmp/tmux.sock -2 new-session -n" .. USER .. " -s" .. USER .. "\""
local xterm = "ghostty -o font.size=5.5 -e " .. SHELL .. " -c          \"tmux -S /tmp/tmux.sock -q has-session &&           exec tmux -S /tmp/tmux.sock -2 attach-session -d ||           exec tmux -S /tmp/tmux.sock -2 new-session -n" .. USER .. " -s" .. USER .. "\""

-- ══════════════════════════════════════════════════════════════════════════════
-- AUTOSTART
-- ══════════════════════════════════════════════════════════════════════════════

-- xdg-desktop-portal (Hyprland 版を先に起動し後から汎用版を置換)

-- DPMS 管理: hypridle (Hyprland ネイティブ、swayidle より統合度が高い)

-- Wallpaper (swww で滑らかなトランジション)

-- ══════════════════════════════════════════════════════════════════════════════
-- RENDERING — NVIDIA explicit sync (driver 555+ / kernel 6.8+)
-- ══════════════════════════════════════════════════════════════════════════════

hl.curve("overshoot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("smooth", { type = "bezier", points = { { 0.25, 1.0 }, { 0.5, 1.0 } } })
hl.curve("snappy", { type = "bezier", points = { { 0.0, 0.85 }, { 0.15, 1.0 } } })
hl.curve("linear", { type = "bezier", points = { { 0.0, 0.0 }, { 1.0, 1.0 } } })
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 5,
    bezier = "overshoot",
    style = "slide",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 4,
    bezier = "snappy",
    style = "popin 80%",
})
hl.animation({
    leaf = "windowsMove",
    enabled = true,
    speed = 4,
    bezier = "smooth",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 8,
    bezier = "linear",
})
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 120,
    bezier = "linear",
    style = "loop",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 4,
    bezier = "snappy",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 3,
    bezier = "snappy",
})
hl.animation({
    leaf = "fadeDim",
    enabled = true,
    speed = 4,
    bezier = "snappy",
})
hl.animation({
    leaf = "fadeLayers",
    enabled = true,
    speed = 4,
    bezier = "snappy",
})
hl.animation({
    leaf = "fadeSwitch",
    enabled = true,
    speed = 4,
    bezier = "snappy",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 5,
    bezier = "smooth",
    style = "slide",
})
hl.animation({
    leaf = "specialWorkspace",
    enabled = true,
    speed = 4,
    bezier = "snappy",
    style = "slidevert",
})

hl.layer_rule({
    match = { namespace = "waybar" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "wofi" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "mako" },   -- mako notification daemon
    blur = true,
})

hl.layer_rule({
    match = { namespace = "gtk-layer-shell" },
    blur = true,
})

hl.layer_rule({
    match = { namespace = "waybar" },
    ignore_alpha = 0.0,   -- ignorezero: 完全透明ピクセルにはブラー不要
})

hl.layer_rule({
    match = { namespace = "wofi" },
    ignore_alpha = 0.0,
})

hl.layer_rule({
    match = { namespace = "mako" },
    ignore_alpha = 0.0,
})

hl.window_rule({
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

hl.window_rule({
    match = {
        float = 1,
    },
    center = true,
})

hl.window_rule({
    match = {
        class = "^(Gimp)$",
    },
    float = true,
    size = "800 600",
})

hl.window_rule({
    match = {
        class = "^(mpv)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^([Vv]lc)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
    size = "40% 30%",
})

hl.window_rule({
    match = {
        title = "^(nmtui)$",
    },
    float = true,
    size = "50% 70%",
})

hl.window_rule({
    match = {
        title = "^(btop)$",
    },
    float = true,
    size = "50% 70%",
})

hl.window_rule({
    match = {
        title = "^(Picture in picture)$",
    },
    float = true,
    pin = true,
})

hl.window_rule({
    match = {
        title = "^(File Operation Progress)$",
    },
    float = true,
    pin = true,
    size = "40% 30%",
})

hl.window_rule({
    match = {
        title = "^(Save File)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        title = "^(About)$",
    },
    float = true,
})

hl.window_rule({
    match = { xdg_portal = true },   -- xdg-portal:1 相当（XDG portal ウィンドウ）
    float = true,
})

hl.window_rule({
    match = {
        class = "^(fcitx-config-gtk3)$",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "^(fcitx-configtool)$",
    },
    float = true,
})

hl.window_rule({
    match = { class = "^(com\\.mitchellh\\.ghostty)$" },
    idle_inhibit = "fullscreen",
})

hl.window_rule({
    match = { class = "^(Google-chrome)$" },
    idle_inhibit = "fullscreen",
})

hl.window_rule({
    match = { class = "^(mpv)$" },
    idle_inhibit = "always",
})

hl.window_rule({
    match = { class = "^([Vv]lc)$" },
    idle_inhibit = "always",
})

hl.window_rule({
    match = {
        class = "^(com\\.mitchellh\\.ghostty)$",
    },
    opacity = "0.9 0.85",
})

hl.window_rule({
    match = {
        class = "^(Google-chrome)$",
    },
    opacity = "0.9 0.85",
})

hl.window_rule({
    match = {
        class = "^(Slack)$",
    },
    opacity = "0.9 0.85",
})

hl.window_rule({
    match = {
        class = "^(discord)$",
    },
    opacity = "0.9 0.85",
})

hl.window_rule({
    match = {
        class = "^(mpv)$",
    },
    opacity = "0.9 0.9",
})

hl.window_rule({
    match = {
        class = "^(Slack)$",
    },
    tag = "+electron",
})

hl.window_rule({
    match = {
        class = "^(discord)$",
    },
    tag = "+electron",
})

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-1",
    default = true,
})

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(term))
hl.bind(mainMod .. " + CTRL + Return", hl.dsp.exec_cmd(xterm))

hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + P", hl.dsp.window.pin())
hl.bind(mainMod .. " + U", hl.dsp.focus({ urgent_or_last = true }))

hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))

hl.bind(mainMod .. " + SHIFT + Return", hl.dsp.dpms({ action = "on" }))
hl.bind(mainMod .. " + SHIFT + Delete", hl.dsp.dpms({ action = "off" }))

hl.bind(mainMod .. " + SHIFT + I", hl.dsp.exec_cmd(term_float .. " -t cheatsheet -e micro ~/.config/sway/cheatsheet.md"))

hl.bind(mainMod .. " + F2", hl.dsp.exec_cmd(chrome))
hl.bind(mainMod .. " + F3", hl.dsp.exec_cmd("slack"))
hl.bind(mainMod .. " + F4", hl.dsp.exec_cmd("discord"))
hl.bind(mainMod .. " + F5", hl.dsp.exec_cmd(chrome .. " --app=https://calendar.google.com/calendar/r"))
hl.bind(mainMod .. " + F6", hl.dsp.exec_cmd(chrome .. " --app=https://mail.google.com/mail/u/0/"))
hl.bind(mainMod .. " + F7", hl.dsp.exec_cmd(chrome .. " --app=https://github.com/kpango"))

hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exit())

hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))

hl.bind(mainMod .. " + SHIFT + H", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + ALT + H", hl.dsp.window.move({ x = -20, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + ALT + J", hl.dsp.window.move({ x = 0, y = 20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + ALT + K", hl.dsp.window.move({ x = 0, y = -20, relative = true }), { repeating = true })
hl.bind(mainMod .. " + ALT + L", hl.dsp.window.move({ x = 20, y = 0, relative = true }), { repeating = true })

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + B", hl.dsp.layout("preselect h"))
hl.bind(mainMod .. " + V", hl.dsp.layout("preselect v"))
hl.bind(mainMod .. " + E", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + M", hl.dsp.layout("swapwithmaster"))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + Space", hl.dsp.window.cycle_next({ next = true }))

hl.bind(mainMod .. " + SHIFT + Minus", hl.dsp.window.move({ workspace = "special" }))
hl.bind(mainMod .. " + Minus", hl.dsp.workspace.toggle_special(""))

hl.bind(mainMod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mainMod .. " + Page_Up", hl.dsp.focus({ workspace = -1 }))
hl.bind(mainMod .. " + Page_Down", hl.dsp.focus({ workspace = "+1" }))

hl.bind(mainMod .. " + R", hl.dsp.submap("resize"))
hl.define_submap("resize", function()
    hl.bind("H", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("J", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("K", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("L", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("Return", hl.dsp.submap("reset"))
    hl.bind("Escape", hl.dsp.submap("reset"))
end)

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())
hl.bind(mainMod .. " + mouse_down", hl.dsp.window.resize({ x = 0, y = -5, relative = true }), { repeating = true })
hl.bind(mainMod .. " + mouse_up", hl.dsp.window.resize({ x = 0, y = 5, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + mouse_down", hl.dsp.window.resize({ x = -5, y = 0, relative = true }), { repeating = true })
hl.bind(mainMod .. " + SHIFT + mouse_up", hl.dsp.window.resize({ x = 5, y = 0, relative = true }), { repeating = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 5%+ && notify-send \"Volume Increased\""))
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%- && notify-send \"Volume Decreased\""))
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && notify-send \"Mute Toggled\""))
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play"))
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl pause"))
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"))
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"))

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("sudo light -A 5 && notify-send \"Brightness Increased\""))
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("sudo light -U 5 && notify-send \"Brightness Decreased\""))

hl.bind("Print", hl.dsp.exec_cmd("grim \"$HOME/Pictures/$(date +'%F-%T')-screenshot.png\""))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("~/.config/sway/scripts/screenshot.sh"))
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("grim -g \"$(slurp)\" \"$HOME/Pictures/$(date +'%F-%T')-screenshot.png\""))
hl.bind(mainMod .. " + CTRL + P", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | wl-copy"))

hl.bind(mainMod .. " + CTRL + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + CTRL + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + CTRL + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + CTRL + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + CTRL + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + CTRL + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + CTRL + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + CTRL + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + CTRL + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + CTRL + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.bind(mainMod .. " + G", hl.dsp.group.toggle())
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.group.lock({ action = "toggle" }))
hl.bind(mainMod .. " + CTRL + H", hl.dsp.group.prev())
hl.bind(mainMod .. " + CTRL + L", hl.dsp.group.next())
hl.bind(mainMod .. " + CTRL + left", hl.dsp.group.prev())
hl.bind(mainMod .. " + CTRL + right", hl.dsp.group.next())
hl.config({
    render = {
        -- explicit_sync / explicit_sync_kms は v0.50 で削除済み（常時 ON のためオプション不要）
        direct_scanout = false, -- NVIDIA では false 推奨（フルスクリーン最適化は VRR で行う）
        -- 動的トリプルバッファリング: フレーム落ち時のみ triple に切替、通常時はレイテンシ無影響 (v0.50+)
        new_render_scheduling = true,
        -- HDR 自動トーンマッピング (v0.55+, 実験的)
        -- Dell U4919DW: EDID に HDR Static Metadata なし = SDR 専用 → false
        -- HDR 対応モニター追加時は true に変更すること
        cm_auto_hdr = false,
    },
    opengl = {
        nvidia_anti_flicker = true, -- NVIDIA フリッカー防止
        force_introspection = 0, -- 0=auto
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- GENERAL
    -- ══════════════════════════════════════════════════════════════════════════════
    general = {
        gaps_in = 4, -- sway: gaps inner 8 (両側で 4 ずつ)
        gaps_out = 2, -- sway: gaps outer 2
        border_size = 2,
        -- Catppuccin Mocha グラデーションボーダー（waybar カラースキームと統一）
        col = {
            active_border = { colors = { "rgba(89b4faff)", "rgba(cba6f7ff)" }, angle = 45 }, -- blue → mauve
            inactive_border = "rgba(313244aa)", -- surface0
        },
        layout = "dwindle",
        allow_tearing = false, -- VRR で代替するため false
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- DECORATION
    -- ══════════════════════════════════════════════════════════════════════════════
    decoration = {
        rounding = 8,
        rounding_power = 2.0,
        -- ── Blur (フロストグラス効果) ────────────────────────────────────────────
        blur = {
            enabled = true,
            -- size=12 passes=2 は size=10 passes=3 と視覚的に同等だが計算量約20%削減
            -- 分離フィルター: 処理量 = passes × size × 2 → 10*3*2=60 vs 12*2*2=48 ops/px
            size = 12,
            passes = 2,
            new_optimizations = true,
            xray = false, -- ウィンドウを透かして見ない（重ね順を尊重）
            noise = 0.015, -- フィルムグレイン（自然な質感）
            contrast = 0.9,
            brightness = 0.85,
            vibrancy = 0.17,
            vibrancy_darkness = 0.0,
            popups = true, -- ポップアップ・ツールチップにもブラー
            popups_ignorealpha = 0.2,
            special = true, -- special workspace の背景にもブラー
            ignore_opacity = false,
        },
        -- ── Shadow ──────────────────────────────────────────────────────────────
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            color = "rgba(1a1a2ecc)",
            color_inactive = "rgba(1a1a2e66)",
            offset = "0, 6", -- 下方向にオフセットして立体感
            scale = 1.0,
        },
        -- ── Dim (非アクティブウィンドウを暗くして奥行き表現) ─────────────────────
        dim_inactive = true,
        dim_strength = 0.08, -- 控えめに（作業の邪魔をしない程度）
        dim_special = 0.15, -- special workspace の暗転
        dim_around = 0.0,
        -- ── Per-app opacity (active / inactive — 0.9 スタート、二分探索で調整) ──
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        fullscreen_opacity = 1.0,
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- ANIMATIONS
    -- ══════════════════════════════════════════════════════════════════════════════
    animations = {
        enabled = true,
        -- ── Bezier カーブ定義 ───────────────────────────────────────────────────
        -- ── ウィンドウ ───────────────────────────────────────────────────────────
        -- ── ボーダー ─────────────────────────────────────────────────────────────
        -- ── フェード ─────────────────────────────────────────────────────────────
        -- ── ワークスペース ────────────────────────────────────────────────────────
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- INPUT
    -- ══════════════════════════════════════════════════════════════════════════════
    input = {
        kb_layout = "us",
        kb_options = "ctrl:nocaps",
        repeat_rate = 30, -- キーリピート速度 (chars/sec)
        repeat_delay = 250, -- リピート開始遅延 (ms)
        follow_mouse = 0, -- focus_follows_mouse no
        mouse_refocus = false,
        accel_profile = "flat", -- ポインタ加速なし（精密操作向け）
        sensitivity = 0.0, -- flat モードでは 0.0 推奨
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true,
            clickfinger_behavior = true,
            drag_lock = true,
            scroll_factor = 0.8,
        },
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- CURSOR
    -- ══════════════════════════════════════════════════════════════════════════════
    cursor = {
        no_hardware_cursors = false, -- NVIDIA 555+ は false で OK（古い driver なら true）
        inactive_timeout = 3, -- 3 秒操作なしでカーソル非表示
        warp_on_change_workspace = false,
        hide_on_key_press = false,
        enable_hyprcursor = true,
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- LAYOUT
    -- ══════════════════════════════════════════════════════════════════════════════
    dwindle = {
        -- pseudotile は v0.55 で削除（per-window のみ: windowrulev2 = pseudo, class:...）
        preserve_split = true,
        smart_split = false,
        smart_resizing = true,
        force_split = 0, -- 0=フォーカス側, 1=右/下, 2=左/上
    },
    master = {
        new_is_master = false,
        mfact = 0.55,
        orientation = "left",
        always_center_master = false,
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- MISC / PERFORMANCE
    -- ══════════════════════════════════════════════════════════════════════════════
    misc = {
        font_family = "HackGen35ConsoleNF",
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        focus_on_activate = false,
        new_window_takes_over_fullscreen = 2, -- popup_during_fullscreen smart 相当
        -- ── VRR (Adaptive Sync) ───────────────────────────────────────────────
        vrr = 2, -- 0=off, 1=always, 2=fullscreen only
        -- vrr=1(always) はマルチモニタ環境で同期タイミング衝突→クラッシュの報告あり
        -- vfr / no_vfr_when_cursor は v0.55 で debug {} へ移動済み（下記 debug ブロック参照）
        -- ── DPMS ────────────────────────────────────────────────────────────────
        mouse_move_enables_dpms = true,
        key_press_enables_dpms = true,
        -- ── Window swallowing (端末から mpv 等を起動すると端末が隠れる) ──────────
        enable_swallow = true,
        swallow_regex = "^(com\\.mitchellh\\.ghostty)$",
        swallow_exception_regex = "^(wev|xev|mpv)$",
        -- ── 挙動 ────────────────────────────────────────────────────────────────
        animate_manual_resizes = true,
        animate_mouse_windowdragging = true,
        always_follow_on_dnd = true,
        close_special_on_empty = true,
        initial_workspace_tracking = 1,
        layers_hog_keyboard_focus = true,
        -- 起動アニメーションをスキップしてログイン後の応答を速める
        first_launch_animation = false,
        -- 壁紙ロード前の背景色（Catppuccin Mocha base — 黒い点滅を防ぐ）
        background_color = "rgba(1e1e2eff)",
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- GESTURES
    -- ══════════════════════════════════════════════════════════════════════════════
    -- ══════════════════════════════════════════════════════════════════════════════
    -- XWAYLAND
    -- ══════════════════════════════════════════════════════════════════════════════
    xwayland = {
        -- XWayland アプリのスケーリングを 1:1 に強制してぼやけを防ぐ
        -- （Slack・Discord 等の Electron アプリはネイティブ Wayland で起動するため無関係）
        force_zero_scaling = true,
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- BINDS
    -- ══════════════════════════════════════════════════════════════════════════════
    binds = {
        -- workspace, previous が端から端へ循環する
        allow_workspace_cycles = true,
        workspace_back_and_forth = true,
        -- スクロールイベントのワークスペース切替デバウンス (ms)
        scroll_event_delay = 300,
        -- ドラッグ中にウィンドウをフロートに自動昇格
        drag_and_drop_windows = true,
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- GROUP (タブグループ — 複数ウィンドウを 1 枠にまとめる)
    -- ══════════════════════════════════════════════════════════════════════════════
    group = {
        col = {
            border_active = { colors = { "rgba(89b4faff)", "rgba(cba6f7ff)" }, angle = 45 },
            border_inactive = "rgba(313244aa)",
            border_locked_active = "rgba(f38ba8ff)", -- Catppuccin red（ロック中）
            border_locked_inactive = "rgba(45475aaa)",
        },
        groupbar = {
            enabled = true,
            font_family = "HackGen35ConsoleNF",
            font_size = 11,
            height = 20,
            text_color = "rgba(cdd6f4ff)",
            col = {
                active = "rgba(89b4faee)", -- blue
                inactive = "rgba(313244ee)", -- surface0
                locked_active = "rgba(f38ba8ee)",
                locked_inactive = "rgba(45475aee)",
            },
            scrolling = true,
            indicator_height = 2,
            render_titles = true,
            gradients = true, -- グループバーにもグラデーション
        },
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- DEBUG (本番環境ではログを無効化して I/O 削減)
    -- ══════════════════════════════════════════════════════════════════════════════
    debug = {
        disable_logs = true, -- journald への書き込み停止（CPU/I/O 削減）
        disable_time = true,
        overlay = false,
        damage_blink = false,
        -- damage_tracking = 2  # デフォルト値、コメントアウトで同効果
        -- VFR (v0.55 で misc → debug へ移動)
        vfr = true, -- Variable Framerate — アイドル時 CPU/GPU 負荷激減
        no_vfr_when_cursor = false, -- カーソル動作中も VFR 維持
    },
    gestures = {
        workspace_swipe = true,
        workspace_swipe_fingers = 3,
        workspace_swipe_distance = 300,
        workspace_swipe_invert = true,
        workspace_swipe_min_speed_to_force = 30,
        workspace_swipe_cancel_ratio = 0.5,
    },
    -- ══════════════════════════════════════════════════════════════════════════════
    -- LAYER RULES — waybar / wofi / mako にもブラーを適用
    -- ══════════════════════════════════════════════════════════════════════════════
    -- ══════════════════════════════════════════════════════════════════════════════
    -- WINDOW RULES
    -- ══════════════════════════════════════════════════════════════════════════════
    -- ── グローバル ──────────────────────────────────────────────────────────────
    -- ── Media ───────────────────────────────────────────────────────────────────
    -- ── System dialogs ───────────────────────────────────────────────────────────
    -- ── Sticky / PiP ─────────────────────────────────────────────────────────────
    -- ── Generic dialogs ──────────────────────────────────────────────────────────
    -- ── fcitx ────────────────────────────────────────────────────────────────────
    -- ── Inhibit idle when fullscreen ─────────────────────────────────────────────
    -- ロック画面なし環境: 動画再生中は常に DPMS を抑制
    -- ── Opacity (active / inactive — 0.9 スタート、二分探索で調整) ───────────────
    -- Hyprland の blur と組み合わせることで Sway より美しいフロストグラス効果になる
    -- ── Electron apps: Wayland ネイティブで起動させるためのルール ────────────────
    -- ══════════════════════════════════════════════════════════════════════════════
    -- WORKSPACE RULES
    -- ══════════════════════════════════════════════════════════════════════════════
    -- ══════════════════════════════════════════════════════════════════════════════
    -- KEYBINDINGS
    -- ══════════════════════════════════════════════════════════════════════════════
    -- ── Terminals ────────────────────────────────────────────────────────────────
    -- ── Window management ─────────────────────────────────────────────────────────
    -- ── Launchers ─────────────────────────────────────────────────────────────────
    -- ── DPMS ─────────────────────────────────────────────────────────────────────
    -- ── Cheatsheet ────────────────────────────────────────────────────────────────
    -- ── App shortcuts (F2–F7) ─────────────────────────────────────────────────────
    -- ── Hyprland management ───────────────────────────────────────────────────────
    -- ── Focus (vim-style) ─────────────────────────────────────────────────────────
    -- ── Window movement ───────────────────────────────────────────────────────────
    -- ── Float window keyboard move (Alt+hjkl) ────────────────────────────────────
    -- ── Workspaces ────────────────────────────────────────────────────────────────
    -- ── Layout ────────────────────────────────────────────────────────────────────
    -- ── Scratchpad (special workspace) ───────────────────────────────────────────
    -- ── Workspace navigation ──────────────────────────────────────────────────────
    -- ── Resize submap (sway mode "resize" 相当) ───────────────────────────────────
    -- ── Mouse ─────────────────────────────────────────────────────────────────────
    -- ── Audio ─────────────────────────────────────────────────────────────────────
    -- ── Brightness ───────────────────────────────────────────────────────────────
    -- ── Screenshots ───────────────────────────────────────────────────────────────
    -- クリップボードへ直接コピー（ファイル保存なし）
    -- ── Silent workspace move (フォーカスを移さずウィンドウだけ送る) ───────────────
    -- ── Group (タブグループ操作) ──────────────────────────────────────────────────
})

hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user import-environment DISPLAY WAYLAND_DISPLAY HYPRLAND_INSTANCE_SIGNATURE XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("sleep 0.5 && /usr/lib/xdg-desktop-portal-hyprland")
    hl.exec_cmd("sleep 1.5 && /usr/lib/xdg-desktop-portal --replace")
    hl.exec_cmd("waybar --config $HOME/.config/waybar/config-hyprland.json --style $HOME/.config/waybar/style.css")
    hl.exec_cmd("mako")
    hl.exec_cmd("fcitx5 -rd")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("systemctl --user start --no-block hyprland-session.target")
    hl.exec_cmd("swww-daemon")
    -- config.reloaded は hyprland.start より前に発火するため初回壁紙は ここで設定する
    hl.exec_cmd("sleep 0.5 && swww img \"$(find -L $HOME/.wallpapers -type f ! -path '*/.git/*' ! -name 'Makefile' ! -name '*.go' ! -name 'go.mod' ! -name 'go.sum' | shuf -n1)\" --transition-type wipe --transition-duration 1.5")
    hl.exec_cmd(term)
end)

hl.on("config.reloaded", function()
    -- reload 時のみ: hyprland.start 後は swww-daemon が起動済みのため即時実行可
    hl.exec_cmd("swww img \"$(find -L $HOME/.wallpapers -type f ! -path '*/.git/*' ! -name 'Makefile' ! -name '*.go' ! -name 'go.mod' ! -name 'go.sum' | shuf -n1)\" --transition-type wipe --transition-duration 1.5")
end)

