
#########################################################################
# PAKKU OVERRIDES
#########################################################################
CARCH=x86_64
PKGDEST=/tmp/pakku-kpango
