export DefaultImModule=fcitx5
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS="@im=fcitx5"
export XMODIFIER="@im=fcitx5"
export LIBSEAT_BACKEND=logind
export SDL_IM_MODULE=fcitx5

