[SystemSettings]
; Smooth out UE4 texture streaming stutter on Proton
r.TextureStreaming=1
r.Streaming.PoolSize=4096
r.Streaming.LimitPoolSizeToVRAM=1
r.Streaming.DefragDynamicBounds=1

; Frame pacing and frame limit (prevents frame spikes and multiplayer stutter)
t.MaxFPS=60

; Motion blur & post-processing adjustment
r.DefaultFeature.MotionBlur=0
r.DepthOfFieldQuality=0

; Anti-aliasing quality (Temporal AA)
r.PostProcessAAQuality=4

[ConsoleVariables]
; UE4 engine garbage collection interval (reduces hitches)
gc.TimeBetweenPurgingPendingKillObjects=60
